"use client";
import React from "react";
import { motion } from "framer-motion";
import { Card, CardHeader, CardBody } from "@heroui/card";

export type Project = {
  title: string;
  subtitle?: string;
  description: string;
  tech?: string[];
  demoLink?: string;
  colorClass?: string;
  // allow string for flexibility when project data comes from different sources
  size?: "sm" | "md" | "lg" | string;
  liveLink?: string;
  password?: string;
};

export default function ProjectCard({ project }: { project: Project }) {
  return (
    <motion.div
      initial={{ opacity: 0, y: 8 }}
      animate={{ opacity: 1, y: 0 }}
      whileHover={{ scale: 1.02, y: -4 }}
      transition={{ duration: 0.35 }}
    >
      {/* compute size and accent */}
      {(() => {
        const sizeClass = project.size === "lg" ? "p-6 md:p-8" : project.size === "sm" ? "p-3" : "p-4";
        const accent = project.colorClass ? project.colorClass : "";
        const cardClass = `w-full ${sizeClass} shadow-sm hover:shadow-lg transition-shadow ${accent}`;

        return (
          <Card className={cardClass}>
            <CardHeader>
              <h2 className="text-xl md:text-2xl font-semibold tracking-tight">{project.title}</h2>
              {project.subtitle && (
                <div className="text-sm text-default-600 mt-1">{project.subtitle}</div>
              )}
            </CardHeader>
            <CardBody>
              <p className="text-base leading-relaxed text-muted-foreground">{project.description}</p>

              {project.tech && project.tech.length > 0 && (
                <div className="flex flex-wrap gap-2 mt-4">
                  {project.tech.map((t) => (
                    <span
                      key={t}
                      className="inline-flex items-center px-2.5 py-1 text-xs font-medium rounded-full bg-default-100 text-default-800 dark:bg-default-800 dark:text-default-200 border border-default-200"
                    >
                      {t}
                    </span>
                  ))}
                </div>
              )}

              {/* derive button bg from colorClass (e.g. border-amber-400 -> bg-amber-400) */}
              {(() => {
                // map known border color tokens to explicit Tailwind bg/text classes
                const knownColorMap: Record<string, { bg: string; text: string }> = {
                  "emerald-400": { bg: "bg-emerald-400", text: "text-default-800" },
                  "amber-400": { bg: "bg-amber-400", text: "text-default-800" },
                  "sky-400": { bg: "bg-sky-400", text: "text-default-800" },
                  "indigo-400": { bg: "bg-indigo-400", text: "text-default-800" },
                };

                const colorToken = (project.colorClass || "")
                  .split(" ")
                  .find((c) => c.startsWith("border-") && !c.startsWith("border-l-"));

                let buttonBg = "bg-foreground";
                let buttonText = "text-background";

                if (colorToken) {
                  const key = colorToken.replace("border-", "");
                  if (knownColorMap[key]) {
                    buttonBg = knownColorMap[key].bg;
                    buttonText = knownColorMap[key].text;
                  } else {
                    // fallback to a bg class constructed from token (may not be generated by Tailwind JIT)
                    buttonBg = colorToken.replace("border-", "bg-");
                    buttonText = "text-default-800";
                  }
                }

                const btnClass = `inline-flex items-center gap-2 px-3 py-1.5 text-sm font-medium rounded-md ${buttonBg} ${buttonText} dark:text-default-800 hover:opacity-95`;

                if (project.demoLink) {
                  return (
                    <div className="mt-4 flex items-center gap-3">
                      <a href={project.demoLink} target="_blank" rel="noreferrer" className={btnClass}>
                        View Demo
                      </a>
                      {project.password && (
                        <span className="text-sm text-default-600">Password: <strong className="ml-1">{project.password}</strong></span>
                      )}
                    </div>
                  );
                }

                if (project.liveLink) {
                  return (
                    <div className="mt-4 flex items-center gap-3">
                      <a href={project.liveLink} target="_blank" rel="noreferrer" className={btnClass}>
                        Live Site
                      </a>
                      {project.password && (
                        <span className="text-sm text-default-600">Password: <strong className="ml-1">{project.password}</strong></span>
                      )}
                    </div>
                  );
                }

                return null;
              })()}
            </CardBody>
          </Card>
        );
      })()}
    </motion.div>
  );
}